sd

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,56 +1,56 @@
 #!/bin/sh
 
-indent() {
-  sed -u 's/^/       /'
-}
+# indent() {
+#   sed -u 's/^/       /'
+# }
 
-touch hello.txt
-echo "-----> Found a hello.txt"
+# touch hello.txt
+# echo "-----> Found a hello.txt"
 
-# if hello.txt has contents, display them (indented to align)
-# otherwise error
+# # if hello.txt has contents, display them (indented to align)
+# # otherwise error
 
-if [ ! -s $1/hello.txt ]; then
-  echo "hello.txt was empty"
-  exit 1
-else
-  echo "hello.txt is not empty, here are the contents" | indent
-  cat $1/hello.txt
-fi | indent
+# if [ ! -s $1/hello.txt ]; then
+#   echo "hello.txt was empty"
+#   exit 1
+# else
+#   echo "hello.txt is not empty, here are the contents" | indent
+#   cat $1/hello.txt
+# fi | indent
 
 
 # #!/usr/bin/env bash
 # # bin/compile <build-dir> <cache-dir>
 # set -e
 
-# BUILD_DIR=$1
-# CACHE_DIR=$2
-# LP_DIR=`cd $(dirname $0); cd ..; pwd`
+BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
-# mkdir -p $CACHE_DIR
-# cd $CACHE_DIR
-# file1="lilypond-2.18.2-1.linux-64.sh"
-# if [ -f $file1 ]
-# then
-#     echo "-----> Download found"
-# else
-# 	echo "-----> Downloading LilyPond"
-# 	curl http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh > $file1
-# 	if [ -f $file1 ]
-# 	then
-# 		echo "-----> Download complete"
-# 	else
-# 	    echo "-----> Download failed. LilyPond installation cannot continue."
-# 	    exit 1;
-# 	fi
-# fi
+mkdir -p $CACHE_DIR
+cd $CACHE_DIR
+file1="lilypond-2.18.2-1.linux-64.sh"
+if [ -f $file1 ]
+then
+    echo "-----> Download found"
+else
+	echo "-----> Downloading LilyPond"
+	curl http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh > $file1
+	if [ -f $file1 ]
+	then
+		echo "-----> Download complete"
+	else
+	    echo "-----> Download failed. LilyPond installation cannot continue."
+	    exit 1;
+	fi
+fi
 
-# # if hash lilypond 2>/dev/null; then
-# # 	echo "-----> LilyPond already installed"
-# # else
-# # 	echo "-----> Installing LilyPond"
-# # 	sh lilypond-2.18.2-1.linux-64.sh --prefix=/app/ --batch
-# # fi
+if hash lilypond 2>/dev/null; then
+	echo "-----> LilyPond already installed"
+else
+	echo "-----> Installing LilyPond"
+	sh lilypond-2.18.2-1.linux-64.sh --prefix=/app/ --batch
+fi
 
 # # echo "-----> Testing LilyPond"
 # # echo \\header{title = \"A scale in LilyPond\"} \\relative {c d e f g a b c} \\version \"2.18.2\" > blah.ly
@@ -64,4 +64,4 @@ fi | indent
 # # 	exit 1;
 # # fi
 
-# echo "-----> Done installing LilyPond"
+echo "-----> Done installing LilyPond"
