modify lilypond test

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -23,15 +23,15 @@ echo $PATH
 # echo 'PYTHONPATH=$PYTHONPATH:$HOME/lilypond/usr/lib/python2.4:$HOME/lilypond/usr/lib/python2.4/plat-linux:$HOME/lilypond/usr/lib/python2.4/lib-dynload' >> $1/.profile.d/LilyPond.sh
 
 ### Lilypond test
-echo "\\header{title = \"A scale in LilyPond\"} \\relative {c d e f g a b c} \\version \"2.20.0\" > blah.ly
+echo '\\header{title = "A scale in LilyPond"} \\relative {c d e f g a b c} \\version "2.20.0"' > blah.ly
+output=blahOutput.png
 lilypond --png -o blahOutput blah.ly
-# if [ -f $file1 ]
-# # then
-# # 	echo "-----> Test passed"
-# # 	rm blah.ly blahOutput.png
-# # else
-# # 	echo "-----> Test failed"
-# # 	exit 1;
-# # fi
-
+if [ -f $output ]
+then
+    echo "-----> Test passed"
+    rm blah.ly blahOutput.png
+else
+    echo "-----> Test failed"
+    exit 1;
+fi
 echo "-----> Done installing LilyPond"
