df

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -23,39 +23,45 @@
 # # bin/compile <build-dir> <cache-dir>
 # set -e
 
-BUILD_DIR=$1
-CACHE_DIR=$2
-LP_DIR=`cd $(dirname $0); cd ..; pwd`
+# BUILD_DIR=$1
+# CACHE_DIR=$2
+# LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
-mkdir -p $CACHE_DIR
-cd $CACHE_DIR
-file1="lilypond-2.18.2-1.linux-64.sh"
-if [ -f $file1 ]
-then
-    echo "-----> Download found"
-else
-	echo "-----> Downloading LilyPond"
-	curl http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh > /app/$file1
-	if [ -f $file1 ]
-	then
-		echo "-----> Download complete"
-	else
-	    echo "-----> Download failed. LilyPond installation cannot continue."
-	    exit 1;
-	fi
-fi
+# mkdir -p $CACHE_DIR
+# cd $CACHE_DIR
+# file1="lilypond-2.18.2-1.linux-64.sh"
+# if [ -f $file1 ]
+# then
+#     echo "-----> Download found"
+# else
+# 	echo "-----> Downloading LilyPond"
+# 	curl http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh > /app/$file1
+# 	if [ -f $file1 ]
+# 	then
+# 		echo "-----> Download complete"
+# 	else
+# 	    echo "-----> Download failed. LilyPond installation cannot continue."
+# 	    exit 1;
+# 	fi
+# fi
 
-if hash lilypond 2>/dev/null; then
-	echo "-----> LilyPond already installed"
-else
-	echo "-----> Installing LilyPond"
-	sh lilypond-2.18.2-1.linux-64.sh --prefix=/app/bin --batch
-fi
+# if hash lilypond 2>/dev/null; then
+# 	echo "-----> LilyPond already installed"
+# else
+# 	echo "-----> Installing LilyPond"
+# 	sh lilypond-2.18.2-1.linux-64.sh --prefix=/app/bin --batch
+# fi
 
+# echo $0
+# cd $HOME
+
+echo "build dir"
 echo $0
-cd $HOME
-curl -O http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh
+echo "cache dir"
+echo $1
 
+cd $1
+curl -O http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh
 echo "-----> Testing LilyPond"
 echo \\header{title = \"A scale in LilyPond\"} \\relative {c d e f g a b c} \\version \"2.18.2\" > blah.ly
 mkdir -p $1/.profile.d
