Testing things

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -32,15 +32,15 @@ else
 fi
 
 echo "-----> Testing LilyPond"
-echo \\header{title = \"A scale in LilyPond\"} \\relative {c d e f g a b c} \\version \"2.18.2\" > blah.ly
-lilypond --png -o blahOutput blah.ly
-if [ -f $file1 ]
-then
-	echo "-----> Test passed"
-	rm blah.ly blahOutput.png
-else
-	echo "-----> Test failed"
-	exit 1;
-fi
+# echo \\header{title = \"A scale in LilyPond\"} \\relative {c d e f g a b c} \\version \"2.18.2\" > blah.ly
+# lilypond --png -o blahOutput blah.ly
+# if [ -f $file1 ]
+# then
+# 	echo "-----> Test passed"
+# 	rm blah.ly blahOutput.png
+# else
+# 	echo "-----> Test failed"
+# 	exit 1;
+# fi
 
 echo "-----> Done installing LilyPond"
